remote_theme: riggraz/no-style-please
title: Seatop's blog
author: seatop
email: seatop@hotmail.com
url: https://www.seatop.com.cn/
baseurl: ""
permalink: /:slug.html
theme_config:
  appearance: "light"
  back_home_text: "返回首页"
  date_format: "%Y-%m-%d"
  show_description: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag

